#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 28 14:41:10 2017

@author: vinnam
"""
import tensorflow as tf

class A:
    #To build the graph when instantiated
    def __init__(self):
        self.graph = tf.Graph()
        with self.graph.as_default():
             self.const = tf.constant([1.0])
    # To launch the graph
    def launchG(self):
        with tf.Session(graph=self.graph) as sess:
             print(sess.run(self.const))
             
class B(A):
    def __init__(self):
        self.graph = tf.Graph()
        with self.graph.as_default():
             self.const = tf.constant([2.0])

A = A()
A.launchG()
B = B()
B.launchG()

a = tf.constant([1.0])
b = tf.constant([2.0])
c = tf.constant([3.0])

sess = tf.InteractiveSession()
X = {a,b,c}
sess.run()