#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 11 15:20:42 2017

@author: vinnam
"""

def test():
    a = 1
    b = 2
    c = 3
    print_var(locals())
    return
def print_var(Vars):
    for var in Vars:
        print Vars[var]
test()